#,プロジェクト,トラッカー,親チケット,ステータス,優先度,題名,作成者,担当者,更新日,カテゴリ,対象バージョン,開始日,期日,予定工数,進捗率,作成日,終了日,関連するチケット,Resolution,Affected version,説明
14650,Redmine,Defect,"",Closed,Urgent,Security vulnerability in Redmine REST API,Wesley Falcao,"",2015-11-27 09:31,Security,"","","","",0,2013-08-08 22:33,2015-11-27 09:31,"",Invalid,2.3.2,"If I login as a non-administrator and try - 

http://localhost:3000/users/

I get a 403 error saying ""You are not authorized to access this page"".

However, logged in as the same user, I can do

http://localhost:3000/users/1.xml
http://localhost:3000/users/2.xml
...
...
...
http://localhost:3000/users/n.xml

And I can access all the users, including their api keys. 

"
14649,Redmine,Patch,"",Closed,Normal,German Translation for r12096,Daniel Felix,"",2015-07-07 12:54,Translations,"","","","",0,2013-08-08 16:32,2015-07-07 12:54,"","","","Hi there,

this is the first part of this translation.
I currently only translated wiki_syntax.html. The other file will follow soon.

Best regards,
Daniel"
14647,Redmine,Patch,"",Closed,Normal,German translation for r12013,Daniel Felix,"",2013-08-09 03:51,Translations,"","","","",0,2013-08-08 15:56,2013-08-09 03:51,"","","","Hi there,

here I am again after my long holidays. ;-)

You find the german translation for r12013. I also restructured the de.yml.

Best regards,
Daniel"
14646,Redmine,Defect,"",Closed,Urgent,"Migrating from Trac, users are not imported",Jack Reacher,"",2013-08-14 10:24,Importers,"","","","",0,2013-08-08 15:44,2013-08-14 10:24,次のチケットと重複 #14590,Duplicate,2.3.2,"The official Redmine from Track migrate plugin should import users (as wrote down here: [[RedmineMigrate#Trac]] ), but it does not. 

In Redmine I see on all ticket that Redmine Admin is the reporter. And reassign 1000 open ticket is a bit painfull. :( 

Environment:
  Redmine version                2.3.2.stable
  Ruby version                   1.9.3-p448 (2013-06-27) [i386-mingw32]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
  Rails Version:                 Rails 3.2.13
  Database:                      MySQL 5.6.13"
14645,Redmine,Patch,"",Closed,Normal,Spanish translations update (r12083),Thomas Godard,"",2013-08-09 03:51,Translations,"","","","",0,2013-08-08 14:44,2013-08-09 03:51,"","","","* Translations added:
** field_must_change_passwd, notice_new_password_must_be_different
"
14633,Redmine,Defect,"",Closed,Urgent,"Internal error on settings, create user, my account and i guess more pages",Doron Sever,"",2013-08-08 10:25,Administration,"","","","",0,2013-08-07 16:30,2013-08-08 10:25,"",Invalid,2.3.2,"Hello
i've upgraded my redmine version from 1.4 to 2.3.2

everything seems to work(all issues and project are there) but i cannot add users nor view ""settings"" page nor view ""My account"" 
i get ""internal error"" page

i've try to google it, gave the whole project 775(i don't mind cuz its only on my dev environment) and still nothing works...

there is nothing on the ""production.log"" file

i don't know if its related but when i try to do this comman: sudo rails server RAILS_ENV=production
i get this error:

@Exiting
/usr/lib/ruby/gems/1.8/gems/rack-1.4.5/lib/rack/handler.rb:63:in `require': no such file to load -- rack/handler/rails__env=production (LoadError)
        from /usr/lib/ruby/gems/1.8/gems/rack-1.4.5/lib/rack/handler.rb:63:in `try_require'
        from /usr/lib/ruby/gems/1.8/gems/rack-1.4.5/lib/rack/handler.rb:16:in `get'
        from /usr/lib/ruby/gems/1.8/gems/rack-1.4.5/lib/rack/server.rb:272:in `server'
        from /usr/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/commands/server.rb:59:in `start'
        from /usr/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/commands.rb:55
        from /usr/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/commands.rb:50:in `tap'
        from /usr/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/commands.rb:50
        from script/rails:6:in `require'
        from script/rails:6
@

Hope someone can help me with that...
"
14631,Redmine,Patch,"",Closed,Normal,Japanese translation update (r12083),Go MAEDA,"",2013-08-08 01:49,Translations,"","","","",0,2013-08-07 16:08,2013-08-08 01:49,"","","",Translated 'field_must_change_passwd' and 'notice_new_password_must_be_different'.
14628,Redmine,Defect,"",Closed,Normal,Deleting saved searches deletes by name.,Dotan Cohen,"",2015-08-23 17:17,Issues,"","","","",0,2013-08-07 13:54,2015-08-23 17:17,"",Cant reproduce,2.1.4,"It seems that Redmine deletes saved Issues searches by name, not by query_id. Thus, when deleting a saved search all saved searches with the same name are deleted."
14627,Redmine,Defect,"",New,Normal,undefined method `show_value' on issues list PDF export,remy H,"",2013-08-07 10:35,PDF export,"","","","",0,2013-08-07 09:21,"","","",2.3.2,"Hello
I had a problem when I tried to export to PDF my issues. Here is the trace :

@NoMethodError (undefined method `show_value'):
  lib/redmine/export/pdf.rb:260:in `block in fetch_row_values'
  lib/redmine/export/pdf.rb:257:in `collect'
  lib/redmine/export/pdf.rb:257:in `fetch_row_values'
  lib/redmine/export/pdf.rb:302:in `block in calc_col_width'
  app/helpers/issues_helper.rb:29:in `block in issue_list'
  app/helpers/issues_helper.rb:25:in `each'
  app/helpers/issues_helper.rb:25:in `issue_list'
  lib/redmine/export/pdf.rb:300:in `calc_col_width'
  lib/redmine/export/pdf.rb:428:in `issues_to_pdf'@

I found what was wrong :

_""include CustomFieldsHelper""_ is missing in _/lib/export/pdf.rb_
 to call _""show_value""_ in _""fetch_row_values""_ method.

Maybe someone should fix this.
"
14626,Redmine,Defect,"",Closed,Normal,Repositories' extra_info column is too short with MySQL,Sergey Vasilyev,Jean-Philippe Lang,2017-04-03 07:33,SCM,3.4.0,"","","",0,2013-08-07 09:03,2017-04-03 07:33,関連している #20127,Fixed,2.3.1,"In the database table repositories a field named ""extra_info"" has type ""text"", which in mysql is limited to 65535 chars. This breaks fetch_changesets command on repositories with a very large amount of branches (git). Actual reason is that is stores only part of the last commit hash or other line (like ""!b"" for ""!binary""), and this causes errors in in fetch_changeset:

<pre>
$ /usr/local/rvm/bin/redmine_rails runner ""Repository.fetch_changesets"" -e production

/usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.13/lib/rails/commands/runner.rb:53:in `eval': comparison of String with nil failed (ArgumentError)
	from /u01/apps/redmine-2.3.1/app/models/repository/git.rb:145:in `fetch_changesets'
	from /u01/apps/redmine-2.3.1/app/models/repository.rb:333:in `block (2 levels) in fetch_changesets'
	from /usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.13/lib/active_record/associations/collection_proxy.rb:89:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.13/lib/active_record/associations/collection_proxy.rb:89:in `method_missing'
	from /u01/apps/redmine-2.3.1/app/models/repository.rb:331:in `block in fetch_changesets'
	from /u01/apps/redmine-2.3.1/app/models/repository.rb:330:in `each'
	from /u01/apps/redmine-2.3.1/app/models/repository.rb:330:in `fetch_changesets'
	from (eval):1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.13/lib/rails/commands/runner.rb:53:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.13/lib/rails/commands/runner.rb:53:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.13/lib/rails/commands.rb:64:in `require'
	from /usr/local/rvm/gems/ruby-1.9.3-p429/gems/railties-3.2.13/lib/rails/commands.rb:64:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
</pre>

Changing the field type to LONGTEXT fixes the problem."
14625,Redmine,Patch,"",Closed,Normal,Traditional Chinese language file (to r12088),ChunChang Lo,"",2013-08-07 09:19,Translations,"","","","",0,2013-08-07 08:50,2013-08-07 09:19,コピー元 #14458,"","","* Translations added:
** field_must_change_passwd, notice_new_password_must_be_different
"
14621,Redmine,Defect,"",Closed,Normal,AJAX call on the issue form resets data entered during the request,Robert Chady,Jean-Philippe Lang,2013-10-10 23:44,UI,2.4.0,"","","",0,2013-08-06 18:21,2013-09-29 12:30,"関連している #13587, 関連している #15125",Fixed,2.3.2,"Running in to an issue where the ajax call being issued when the status dropdown box is updated is causing data to be lost due to the delay.

To reproduce, make a status change in the status dropdown and then pretend you don't see the faint 'Loading' indicator and update the assigned_to field.  When the ajax call completes for the change to status_id it will lose the assigned_to change.  The Loading indicator is faint enough that it is very easy to miss it and the delay from that call is significant enough that it easily can trip up people making a lot of changes in the system.

Older Redmine did not have an ajax call on field update so this was never an issue before.  Is there a way this can be changed so it does not cause the delay for that ajax call, or have the ajax call removed entirely?  (I did not see what its use was with my cursory examination of it)"
14615,Redmine,Defect,"",Closed,Normal,Warn me when leaving a page with unsaved text doesn't work when editing an update note,Thomas Godard,Jean-Philippe Lang,2013-08-05 20:32,UI,2.4.0,"","","",0,2013-08-05 10:38,2013-08-05 20:32,"",Fixed,2.3.1,"

Hello,

Just to know, I have made some little tests about the ability of Redmine to prevent a user to leave a page with unsaved text. It works quite well except for one type of update.

When you go and edit an issue update note, you can change page without any warning.

Is this a bug of my instance or is it just not implemented ?

Thanks


See http://www.redmine.org/boards/2/topics/38980"
14612,Redmine,Defect,"",Closed,Normal,Open Issue by email. Attachments are missing,Alex Shemshurenko,"",2013-08-04 16:16,Attachments,"","","","",0,2013-08-04 13:44,2013-08-04 16:16,"",Invalid,2.3.0,"Hi.
Im using Redmine 2.3.0 server. 
Server configured to check for new emails on IMAP server (using chron service).
When i try to open new issue by sending mail i cant see any mail attachments in newly opened issue.
I send email to redmine.In mail i define project and tracker.

  Project: newproject
  Tracker: Bug

I add text file as attachment to email.

After some time i can see new issue opened in project ""newproject"" in tracker ""Bug"", but text file attachment is missing.
Im sure its some kind of configuration error, but i dont know where to start looking for the porblem."
14607,Redmine,Defect,"",Closed,Normal,rake redmine:load_default_data Error,jun yang,Jean-Philippe Lang,2013-08-04 20:48,Administration,2.3.3,"","","",0,2013-08-03 12:34,2013-08-04 12:33,"",Fixed,"","Hi,when I install redmine,execute RAILS_ENV=production rake redmine:load_default_data,
Error:undefined method 'association_class' for nil:NilClass

Environment:
Redmine version 2.3.1.stable
Ruby version 1.9.3 (x86_64-linux)
Rails version 3.2.13
Environment production
Database adapter Mysql2
Centos 6.4 (Final)
"
14606,Redmine,Patch,"",Closed,Normal,"Internal error when copying an issue + on ""my page"" in block ""assigned to me""",Mattanja Kern,"",2013-09-24 10:42,Issues,"","","","",0,2013-08-02 23:25,2013-08-05 05:23,関連している #14939,"","","I stumbled upon an issue in the latest svn version of Redmine and have attached a small path for the problem. You might want to look for the root cause of the issue since obviously my fix is probably only a workaround:

    -          user_ids = [user.id] + user.groups.map(&:id)
+          user_ids = [user.id] + user.groups.map(&:id).reject(&:nil?

    $ svn info
Path: .
URL: http://svn.redmine.org/redmine/trunk
Repository Root: http://svn.redmine.org/redmine
Repository UUID: e93f8b46-1217-0410-a6f0-8f06a7374b81
Revision: 12072
Node Kind: directory
Schedule: normal
Last Changed Author: tmaruyama
Last Changed Rev: 12072
Last Changed Date: 2013-08-01 05:31:54 +0200 (Thu, 01 Aug 2013)

    Environment:
  Redmine version                2.3.2.devel.12072
  Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.7
  redmine_lightbox               0.0.1

> Completed 500 Internal Server Error in 35ms
> 
> ActionView::Template::Error (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')))) OR (projects.id IN (23,1,24,22) AND ((issues.is_private = 0 OR issues.autho' at line 1: SELECT COUNT(DISTINCT `issues`.`id`) FROM `issues` LEFT OUTER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` LEFT OUTER JOIN `issue_statuses` ON `issue_statuses`.`id` = `issues`.`status_id` WHERE (((projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking')) AND ((projects.is_public = 1 AND ((issues.is_private = 0 OR issues.author_id = 87 OR issues.assigned_to_id IN (87,85,)))) OR (projects.id IN (23,1,24,22) AND ((issues.is_private = 0 OR issues.author_id = 87 OR issues.assigned_to_id IN (87,85,)))) OR (projects.id IN (20) AND ((issues.is_private = 0 OR issues.author_id = 87 OR issues.assigned_to_id IN (87,85,)))) OR (projects.id IN (21) AND ((issues.is_private = 0 OR issues.author_id = 87 OR issues.assigned_to_id IN (87,85,))))))) AND (issue_statuses.is_closed = 0) AND ((`issues`.`assigned_to_id` IN (87, 85) OR `issues`.`assigned_to_id` IS NULL))):
> 1: <h3>
> 2:   <%= link_to l(:label_assigned_to_me_issues),
> 3:         issues_path(:set_filter => 1, :assigned_to_id => 'me', :sort => 'priority:desc,updated_on:desc') %>
> 4:   (<%= Issue.visible.open.where(:assigned_to_id => ([User.current.id] + User.current.group_ids)).count %>)
> 5: </h3>
> 6: 
> 7: <% assigned_issues = issuesassignedtome_items %>
> app/views/my/blocks/_issuesassignedtome.html.erb:4:in `_app_views_my_blocks__issuesassignedtome_html_erb___3305484256914345155_39797900'
> app/views/my/page.html.erb:11:in `block in _app_views_my_page_html_erb__2950117810366781438_39717000'
> app/views/my/page.html.erb:8:in `each'
> app/views/my/page.html.erb:8:in `_app_views_my_page_html_erb__2950117810366781438_39717000'
> "
14603,Redmine,Defect,"",Closed,Normal,Start Date and Due Date fields are empty even after inserting the valuess,Raghu GS,"",2017-06-04 06:02,Issues,"","","","",0,2013-08-02 11:11,2017-06-04 06:02,"",Cant reproduce,2.3.2,"I am using Redmine v2.3x, the start date and due date are returning empty date even if i submit correct values to it."
14598,Redmine,Defect,"",Closed,Normal,Wrong test with logger.info in model mail_handler,J?r?me BATAILLE,"",2013-11-12 11:12,Email receiving,2.4.0,"","","",0,2013-08-01 15:33,2013-11-12 11:12,関連している #9102,Fixed,"",""
14595,Redmine,Defect,"",Closed,Normal,CSV don't use filter for some users,Johan Guilbaud,"",2014-05-13 07:51,Issues,"","","","",0,2013-08-01 11:33,2014-05-13 07:51,"","",2.2.3,"Hello

Fisrt sorry for my bad english it's not my native language

I have a bug about CSV export with filters for some users

tests i made :
myaccount : admin
the user is manager of his projects

When go on Issues page there is 700 issues

After applying a filter there is 200 issues
when the user export in CSV he get 700issues  => CSV have not used filters
if i export issues in CSV with my admin account i get the 200 issues shown on the web page

we've made the tests on 2 computers (Windows Seven with Firefox 16)

thanks for helping


--------------------------------------------------------------------
=> Redmine is on a RHEL6 with Apache 2 & mod_passenger

Environment:
  Redmine version                          2.2.3.stable
  Ruby version                             1.8.7 (x86_64-linux)
  Rails version                            3.2.12
  Environment                              production
  Database adapter                         MySQL
Redmine plugins:
  redmine_charts2                          0.2.1
  redmine_default_columns                  0.1.1
  redmine_wiki_unc                         0.0.3"
14594,Redmine,Defect,"",Closed,Normal,Pictures in email notification,Tory Wolf,"",2013-08-01 10:36,Email notifications,"","","","",0,2013-08-01 10:19,2013-08-01 10:36,"",Invalid,2.3.1,"Hello Redmine Team,

If I add a picture in the issue description, it won't be displayed in email body.
I guess, the reason is the tag <p>, source of email looks like:

@<p><img src=""http://sci-tech.in/wp-content/uploads/2011/07/derevo-219x300.jpg"" alt="""" /></p>@"
14593,Redmine,Patch,"",New,Normal,"migrate_from_trac.rake, print out validation errors when doing save",Craig Rodrigues,"",2013-10-13 06:28,Importers,"","","","",0,2013-08-01 09:53,"",関連している #14567,"","","In the migrate_from_trac.rake script,
the save method is called on several objects
to save them to the database.  However, if these
objects fail validation, the object is not saved to the database.
The errors are not displayed to the user, and
the migrate_from_trac.rake script will skip saving
many different objects to the database.

This patch preserves the behavior of skipping saving certain
objects if they fail validation, but the patch
will at least try to print out the errors.  This will
give the user a chance to scrub the data in Trac
so that it can be properly imported into Redmine.

During my test imports of a large Trac database into Redmine,
I was wondering why certain users and certain tickets were
not being imported into Redmine.

Related to #14567"
14592,Redmine,Patch,"",Closed,Normal,migrate_from_trac.rake does not properly parse First Name and Last Name,Craig Rodrigues,"",2013-10-13 10:26,Importers,2.3.4,"","","",0,2013-08-01 09:08,2013-10-13 10:26,関連している #14567,"","","In migrate_from_trac.rake, there is this code:

          name =~ (/(.*)(\s+\w+)?/)
          fn = $1.strip
          ln = ($2 || '-').strip

The regular expression breaking up name is wrong.  (.*) will match the whole
string, so the entire name is set to $1, so the entire name gets assigned
to fn, and ln is blank.

The attached patch fixes that.  Also, I ran into one case where
the name was empty, so $1.strip threw an exception.  I fixed that too with
the attached patch.

Related to #14567"
14590,Redmine,Defect,"",Closed,Normal,"migrate_from_trac.rake does not import Trac users, uses too short password",Craig Rodrigues,Jean-Philippe Lang,2013-10-13 10:25,Importers,2.3.4,"","","",0,2013-08-01 07:41,2013-10-13 10:25,"関連している #14567, 関連している #14960, 次のチケットが重複 #14646",Fixed,"","I was testing migrate_from_trac.rake and found that it was not importing the user database from trac.
I substituted "".save"" with "".save!"" in a few places in the script and found this error:

Validation failed: Password is too short (minimum is 8 characters)
/usr/local/lib/ruby/gems/1.9/gems/activerecord-3.2.13/lib/active_record/validations.rb:56:in `save!'
/usr/local/lib/ruby/gems/1.9/gems/activerecord-3.2.13/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/usr/local/lib/ruby/gems/1.9/gems/activerecord-3.2.13/lib/active_record/transactions.rb:264:in `block in save!'
/usr/local/lib/ruby/gems/1.9/gems/activerecord-3.2.13/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/usr/local/lib/ruby/gems/1.9/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/usr/local/lib/ruby/gems/1.9/gems/activerecord-3.2.13/lib/active_record/transactions.rb:208:in `transaction'
/usr/local/lib/ruby/gems/1.9/gems/activerecord-3.2.13/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/usr/local/lib/ruby/gems/1.9/gems/activerecord-3.2.13/lib/active_record/transactions.rb:264:in `save!'
/usr/local/www/redmine/lib/tasks/migrate_from_trac.rake:280:in `find_or_create_user'
/usr/local/www/redmine/lib/tasks/migrate_from_trac.rake:435:in `block in migrate'
/usr/local/www/redmine/lib/tasks/migrate_from_trac.rake:428:in `each'
/usr/local/www/redmine/lib/tasks/migrate_from_trac.rake:428:in `migrate'


Changing the default password for created users from 'trac'
to 'tracmigratetoredmine' fixed the problem.

See attached patch.

Related to: #14567
"
14588,Redmine,Patch,"",Closed,Normal,Add example on how to run a single test to documentation,Mischa The Evil,"",2013-08-01 05:34,Documentation,"","","","",0,2013-08-01 03:14,2013-08-01 05:34,"","","","A tiny[1] documentation update to add a new example on how to run a single test. The idea came up after seeing ""OpenProject-commit:45ab6858"":https://github.com/opf/openproject/commit/45ab68581d799d9ecb8057b5544b3a5d0a7f4473 and remembering myself looking up the option repeatedly in the past.

<pre><code class=""diff"">
Index: doc/RUNNING_TESTS
===================================================================
--- doc/RUNNING_TESTS	(revision 12071)
+++ doc/RUNNING_TESTS	(working copy)
@@ -11,7 +11,8 @@
 Run `rake test` to run the entire test suite (except the tests for the
 Apache perl module Redmine.pm and Capybara tests, see below).
 
-You can run `ruby test/unit/issue_test.rb` for running a single test case.
+You can run `ruby test/unit/issue_test.rb` for running a single test case and
+`ruby test/unit/issue_test.rb -n test_create` for running a single test.
 
 Before running tests, you need to configure both development
 and test databases.
</code></pre>

fn1. so small that I won't attach a patch file... ;)"
14587,Redmine,Defect,"",Closed,Normal,esclusione funzione call center,Luca Ferrari,"",2013-07-31 23:16,"","","","","",0,2013-07-31 17:23,2013-07-31 23:16,"",Invalid,"","ciao, mi servirebbe gentilmente, a seguito di richiesta fatta dallo stesso, di togliere Andrea Trevisan dalla funzione di notifica tramite mail a seguito del flag posto nel call center ""segnala a isp. caf"".
Resto collegato io, Ferrari Luca, mentre Andrea avr? la funzione di ""segnala RRR"" per la sua zona di competenza.

grazie"
14586,Redmine,Defect,"",Closed,Normal,TCC,Antonio Carlos Rodrigues,"",2013-07-31 23:17,Administration,"","","","",0,2013-07-31 17:14,2013-07-31 23:17,"",Invalid,"",Desenvolvimento TCC
14585,Redmine,Defect,"",Closed,Normal,Problem in redmine icalender export plugin,Piyush Singhal,"",2013-07-31 23:43,"","","","","",0,2013-07-31 15:21,2013-07-31 23:43,"",Invalid,1.0.4,"I am trying to install Redmine ICalendar Export Plugin(https://github.com/planio/redmine_icalendar_export) and this plugin require icalendar, I tried to install it using ""gem install icalendar"" . But after installation calender part stopped working and showing error ""Internal error An error occurred on the page you were trying to access."" 

In the log file I am getting following error:

ActionView::TemplateError (No route matches {:action=>""index"", :status=>""all"", :controller=>""calendar"", :assigned_to=>""*"", :format=>""atom"", :project_id=>#<Project id: 3, name: ""test project"", description: """", homepage: """", is_public: true, parent_id: nil, created_on: ""2013-01-08 06:03:05"", updated_on: ""2013-02-16 04:02:42"", identifier: ""testproject"", status: 1, lft: 5, rgt: 6>, :key=>""268944ce53edddhsjhhgyuh57678dff5f3a0db719323c""}) on line #5 of vendor/plugins/redmine_icalendar_export-master/app/views/hooks/redmine_icalendar_export/_view_calendars_show_bottom.html.erb:

2:      <% other_formats_links do |f| %>
3: <%= f.link_to 'ICS', :url => { :status => 'all',  :assigned_to => '*', :controller => 'calendar', :action => 'index', :project_id => @project, :key => User.current.rss_key, :format => 'atom' } %>
6:      <% end %>
7: <% end %>"
14584,Redmine,Defect,"",Closed,Normal,Standard fields disabled for certain trackers still appear in email notifications,Dmitry Beloglazov,Jean-Philippe Lang,2013-09-10 18:44,Email notifications,2.3.3,"","","",0,2013-07-31 12:45,2013-09-10 18:44,次のチケットに後続 #1091,Fixed,2.3.2,"Hello,

I've created a custom tracker and disabled the ""Target version"" for it. However, the email notifications show it along with other fields.

The expected behavior: the disabled fields don't appear in email notifications.

Environment:
  Redmine version                2.3.2.stable.12032
  Ruby version                   1.8.7-p174 (2009-06-12) [i686-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2"
14578,Redmine,Defect,"",Closed,Normal,After an update from 1.4.3 to 2.3.2 german umlauts in custom fields are broken,ITF-EDV Admin,"",2016-11-21 04:55,Custom fields,"","","","",0,2013-07-30 17:24,2016-11-21 04:55,"","",2.3.2,"The update of all components went fine but all german umlauts only in the customs fields (we added some lists) were broken.
The umlauts in the GUI are ok.

If i add another custom field after the update the umlauts in this new field are fine. Even if i edit our lists the edited umlauts are ok. But i don't want to edit a few hundred entries manually and brake database relationships eventually.

The database is (and was before the update) in utf8 format and the umlauts are correctly stored in the DB.

Environment:
Redmine version                2.3.2.stable
Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
Rails version                  3.2.13
Environment                    production
Database adapter               Mysql2
"
14576,Redmine,Defect,"",New,Normal,fetch_changesets on git push can fail,C Tibirna,"",2013-07-30 16:49,SCM,"","","","",0,2013-07-30 16:49,"","","",2.3.2,"We have a little git hook that calls ""rake redmine:fetch_changesets"" at each successful push in our git server.

All functioned well for a few months, then we got the error message listed below.

The particular push that triggered the error is not different in any particular way. It is a merge and it touched an above average number of files, but such commits we did have before in this repo.

There is no visible adverse effect in the Repository page.
 
<pre>
remote: rake aborted! 
remote: Mysql::Error: Duplicate entry '22-b93e98954d4f843238035a9f73e053c2da122604' for key 'changesets_repos_rev': INSERT INTO `changesets` (`comments`, `commit_date`, `committed_on`, `committer`, `repository_id`, `revision`, `scmid`, `user_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?) 
remote: /pmi/bibgit/webpages/redmine/app/models/repository/git.rb:222:in `save_revision' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository/git.rb:211:in `save_revisions' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository/git.rb:208:in `save_revisions' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository/git.rb:207:in `each' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository/git.rb:207:in `save_revisions' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository/git.rb:154:in `fetch_changesets' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository.rb:333:in `fetch_changesets' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository.rb:331:in `fetch_changesets' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository.rb:330:in `each' 
remote: /pmi/bibgit/webpages/redmine/app/models/repository.rb:330:in `fetch_changesets' 
remote: /pmi/bibgit/webpages/redmine/lib/tasks/redmine.rake:47 
remote: Tasks: TOP => redmine:fetch_changesets 
remote: (See full trace by running task with --trace) 
</pre>"
14575,Redmine,Defect,"",New,Low,"Validation message ""Related issue can't be blank"" should be hidden after ""Add""",Oleg Aksenov,"",2013-07-30 16:34,Issues,"","","","",0,2013-07-30 16:34,"","","",2.3.2,"After trying to add invalid issue number (e.g. non-existent) as related, I saw validation message ""Related issue can't be blank"". It's OK (although it's not blank but invalid).

But, after clicking on ""Add"" I still see this validation message.

Environment:  
  Redmine version                2.3.2.stable.12071
  Ruby version                   1.9.3-p448 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2"
14573,Redmine,Defect,"",Closed,Normal,I can not change the time of update in 'issues view',Sergey Ivanov,"",2013-08-01 04:44,"","","","","",0,2013-07-30 15:39,2013-08-01 04:44,"",Invalid,"",I can not change the time of update in 'issues view' with 'Updated %d days ago.' to 'yyyy-mm-dd'
14571,Redmine,Defect,"",New,Normal,"When updating an issue, start and end date are invalid",Rick Mason,"",2013-07-30 12:48,Issues,"","","","",0,2013-07-30 12:48,"","","",2.3.2,"I have just upgraded from Redmine 2.2.0 to 2.3.2. Since upgrading, when we click Update on an issue the Start Date and End Date fields load in the following format:

Wed Mar 28 00:00:00 +0100 2012

When we save the issue we get ""Start date is not a valid date"" and ""Due date is not a valid date"". The workaround is to reselect both dates from the pop-up calendars so that they're populated in YYYY-MM-DD format. How can we get the dates to load in YYYY-MM-DD format in the first place?

Our setup is Ruby 1.8.7 / Rails 3.2.13 / Redmine 2.3.2 / SQL Server 2005.

I know SQL Server 2005 isn't supported (we're trying to find a 2008 or better server to move it to) but this was working on 2005 before the upgrade."
14567,Redmine,Patch,"",New,Normal,migrate_from_trac.rake does not convert timestamps in Trac database version 23,Craig Rodrigues,"",2013-10-08 04:01,Importers,"","","","",0,2013-07-29 16:46,"","関連している #5764, 関連している #8690, 関連している #12477, 関連している #14590, 関連している #14592, 関連している #14593, 関連している #14844, 関連している #6868, 関連している #10738, 関連している #20943, 次のチケットが重複 #14845, 次のチケットが重複 #17898","","","In Trac API 0.12, the representation of timestamps was changed from seconds since the epoch
to microseconds since the epoch:
http://trac.edgewall.org/wiki/TracDev/ApiChanges/0.12#Timestampstorageindatabase

See this patch that changed it in Trac:

http://trac.edgewall.org/attachment/ticket/6466/6466-microsecond-times-r8770.patch

If you try to run the existing migrate_from_trac.rake script, the year will be thousands
of years in the future, and the importer will populate the date in redmine is 0000000000.
This causes many things to break.
The problem still exists with the trunk version of the migrate_from_trac.rake script.

In #882 , the user encountered the problem, but went down the wrong path with the fix,
because he didn't understand why timestamps were being imported incorrectly.

I am submitting a better fix, which detects the database version of Trac.  If the database
version is > 22, then every time a timestamp from Trac is encountered, we divide by 1 million.

This patch is against trunk.
I have used this patch successfully and it fixes all my problems importing from Trac.

I think many people are hitting these issues when doing Trac -> Redmine migrations.  Here are some example tickets:

#5764
#8690
#12477

"
14565,Redmine,Defect,"",Closed,Urgent,unable to remove file from wiki,匿名ユーザー,"",2013-07-29 10:58,Website (redmine.org),"","","","",0,2013-07-29 09:51,2013-07-29 10:58,"",Invalid,"","hi. i am unable to remove file uploaded to wiki. 
there is no trash icon. "
14562,Redmine,Defect,"",Closed,Normal,diff of CJK (Chinese/Japanese/Korean) is broken on Ruby 1.8,Toshi MARUYAMA,"",2013-07-29 00:10,"",2.3.3,"","","",0,2013-07-28 12:46,2013-07-29 00:10,"","",2.3.2,"From #13644#note-10.

Correct:

!correct.png!

Broken:

!broken.png!"
14557,Redmine,Defect,"",Closed,Normal,Error (stack level too deep) when creating new project,nikos korfiatis,"",2013-08-03 04:52,Projects,"","","","",0,2013-07-27 16:52,2013-08-03 04:52,"",Invalid,2.2.4,"I receive the following error when i try to create a new project. 
Is it related to a plugin ? 




Completed 500 Internal Server Error in 100ms

SystemStackError (stack level too deep):
  app/models/project.rb:290:in `base_reload'
  app/models/project.rb:301:in `base_reload'
  app/models/project.rb:301:in `reload'
  lib/plugins/awesome_nested_set/lib/awesome_nested_set/awesome_nested_set.rb:485:in `reload_nested_set'
  lib/plugins/awesome_nested_set/lib/awesome_nested_set/awesome_nested_set.rb:494:in `move_to'
  lib/plugins/awesome_nested_set/lib/awesome_nested_set/awesome_nested_set.rb:426:in `in_tenacious_transaction'
  lib/plugins/awesome_nested_set/lib/awesome_nested_set/awesome_nested_set.rb:492:in `move_to'
  lib/plugins/awesome_nested_set/lib/awesome_nested_set/awesome_nested_set.rb:491:in `move_to'
  lib/plugins/awesome_nested_set/lib/awesome_nested_set/awesome_nested_set.rb:351:in `move_to_left_of'
  app/models/project.rb:1010:in `set_or_update_position_under'
  app/models/project.rb:1000:in `update_position_under_parent'
  app/controllers/projects_controller.rb:83:in `create'
"
14556,Redmine,Defect,"",Closed,Normal,SCM check: command not found,Pascal H,"",2013-07-27 18:02,SCM,"","","","",0,2013-07-27 16:19,2013-07-27 17:49,"",Invalid,2.3.2,"It would be nice to disable all SCM's by default to prevent these log entrys:

<pre>
[ 2013-07-27 03:27:22.7109 6720/7fc00e758700 Pool2/Implementation.cpp:1182 ]: [App 7993 stderr] sh: svn: command not found
[ 2013-07-27 03:27:22.7150 6720/7fc00e758700 Pool2/Implementation.cpp:1182 ]: [App 7993 stderr] sh: darcs: command not found
[ 2013-07-27 03:27:22.7212 6720/7fc00e758700 Pool2/Implementation.cpp:1182 ]: [App 7993 stderr] sh: hg: command not found
[ 2013-07-27 03:27:22.7258 6720/7fc00e758700 Pool2/Implementation.cpp:1182 ]: [App 7993 stderr] sh: cvs: command not found
[ 2013-07-27 03:27:22.7310 6720/7fc00e758700 Pool2/Implementation.cpp:1182 ]: [App 7993 stderr] sh: bzr: command not found
</pre>

(I use and have installed only git)"
14554,Redmine,Defect,"",New,Normal,Diffs from subprojects return 404,Vitaly vit9696,"",2014-02-16 13:25,SCM,"","","","",0,2013-07-26 19:39,"","","",2.3.2,"Hello, thanks for developing Redmine. I am experiencing a bug with per-file diff and file view urls in revision pages which return 404 (not found). Let me try to explain how to reproduce it:

1) Create a project and a subproject
2) Add repositories (we are using svn) to project and subproject:
Project: svn://host/myrepository with id repository
Subproject svn://host/myrepository/folder with id sub-repository
3) Commit something into svn://host/myrepository/folder
4) Two entries appear in activity list in project and one in subproject
5) The project entry is fine but the subproject entry has wrong urls (accessing from both places) to files and diffs
http://host/redmine/projects/subproject/sub-repository/revisions/1/entry/folder/myfile.cpp
http://host/redmine/projects/subproject/sub-repository/revisions/1/diff/folder/myfile.cpp
instead of
http://host/redmine/projects/subproject/sub-repository/revisions/1/entry/myfile.cpp
http://host/redmine/projects/subproject/sub-repository/revisions/1/diff/myfile.cpp
or 
http://host/redmine/projects/subproject/repository/revisions/1/entry/folder/myfile.cpp
http://host/redmine/projects/subproject/repository/revisions/1/diff/folder/myfile.cpp

Basic information about my installation:
Environment:
  Redmine version                2.3.2.stable.12037
  Ruby version                   1.9.3-p448 (2013-06-27) [i386-darwin10]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  no plugin installed
However, I was able to reproduce it on older versions too."
14550,Redmine,Defect,"",Closed,Normal,"Issue edition : accesskey=""e"" conflict between update link and textarea edit",Vincent Caron,"",2013-07-27 14:18,UI,"","","","",0,2013-07-26 11:02,2013-07-27 14:18,次のチケットと重複 #12684,Duplicate,2.2.2,"I was wondering why the accesskey=""e"" was not working on /issues/:id and discovered that the issue_description textarea already registers the accesskey=""e"" shortcut.

In my case (Chromium 28), the shortcut ends up disabled (it neither clicks 'Update' nor focus on the textarea).

Two possible issues :
* rename the ticket update shortcut, maybe as accesskey=""u""
* remove the textarea accesskey=""e"" which is actually useless in ticket edition mode"
14549,Redmine,Defect,"",Closed,Normal,i do not know if it is a bug,qiye lu,"",2013-07-27 11:46,"","","","","",0,2013-07-26 10:23,2013-07-27 11:46,関連している #2177,Invalid,"","These days,i install the Redmine in my computer.
I have encountered a lot of problems.
One of the problems is that 
in the source of the redmine,there is a function in config\environment.rb:

module ActionView
  module Helpers
    module TextHelper
      def truncate(text, length = 30, truncate_string = ""..."")
        if text.nil? then return end
        l = length-truncate_string.chars.to_a.size
        (text.chars.to_a.size > length ? text.chars.to_a[0...l].join + truncate_string : text).to_s
      end
    end
  end
end

The function truncate is used in app\views\activities\index.html.erb and other files,the source code in 
app\views\activities\index.html.erb is:

<%= format_activity_description(e.event_description) %>
and the last line function format_activity_description is defined in:
app/helpers/application_helper.rb, `format_activity_title,the source code is:

def format_activity_title(text)
    h(truncate_single_line(text, :length => 100))
end

the function truncate_sigle_line is also defined in app/helpers/application_helper.rb,the source code is:
def truncate_single_line(string, *args)
    truncate(string.to_s, *args).gsub(%r{[\r\n]+}m, ' ')
end

the second param of the function truncate is a type of hash
but the param is defined in the function truncate a 'number' type,

that is the issue i have found,but i do not know if it is my version of redmine.
ruby version:ruby 1.8.7"
14546,Redmine,Defect,"",Closed,Normal,Maximum number of items in Atom feeds of redmine.org (25) is too little.,Toshi MARUYAMA,Jean-Philippe Lang,2013-07-28 22:51,Website (redmine.org),"","","","",0,2013-07-26 00:53,2013-07-28 22:51,"","","","I switched from google reader to ""theoldreader"":http://theoldreader.com .
theoldreader was ""down"":http://blog.theoldreader.com/post/56209408824/important-update three days.
I lost many feeds.

redmine.org activity is high in Japanese midnight.
In case of client RSS reader (e.g. thunderbird),
I lose feeds in offline.

Please extend RSS feed limit of redmine.org."
14545,Redmine,Defect,"",Closed,Normal,Mail notifications sent for recent projects only (created after setting up the SMTP connection),Franck Theeten,"",2013-07-28 23:12,Email notifications,"","","","",0,2013-07-25 20:29,2013-07-28 23:12,"",Cant reproduce,2.3.2,"Dear all,

I'm new to Redmine and use Redmine 2.3.3 on Ubuntu 10.04 with MySQL.
I've created a project and set up an asynchrnous connection to a SMTP server for mail notifications. 
My ""default notification"" option is ""For any event on all my projects"" and I've enabled all the actions.
I receive the test mail and the notifications for newly created users.
However I do not receive any notification on the events related to the already existing project.
I've created a new ""test"" projet and began to receive some notification on issues.
It seems there is a bug preventing to retroactively send tthe notifications for the project created before setting up the SMTP connection.

  "
14543,Redmine,Defect,"",Closed,Urgent,db migrate 2.2.3 version sql,arul baskar,"",2013-07-28 12:41,"","","","","",0,2013-07-25 13:48,2013-07-28 12:41,"",Invalid,"","rake aborted!
undefined method `find_by_name' for Setting(Table doesn't exist):Class
D:/redmine2.3.2/app/models/setting.rb:171:in `find_or_default
'
D:/redmine2.3.2/app/models/setting.rb:108:in `[]'
D:/redmine2.3.2/app/models/setting.rb:137:in `plugin_redmine_
pluginname'
D:/redmine2.3.2/plugins/pluginname/init.rb:95:in `block i
n <top (required)>'
D:/redmine2.3.2/config/environment.rb:14:in `<top (required)>
'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
"
14539,Redmine,Defect,"",Closed,High,redmine_time_tracking plugin,Plamen Borisov,"",2013-07-26 08:19,"","","","","",0,2013-07-25 09:12,2013-07-26 08:19,"",Invalid,"","Hello, 

I installed redmine version 2.3.1-3 on new CentOS 6.4 server and wish to use time_tracking plugin. 
Manage to install the plugin - so far so good. No problems starting the timer, but when I try to stop it this error popped up :

Booking could not be added!

Here is my server installation information:

Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_time_tracker                     0.7.0

Thank you in advance for the help !"
14533,Redmine,Defect,"",Closed,Normal,"""Close completed versions"" button not working",Thomas Godard,"",2013-07-29 09:19,Roadmap,"","","","",0,2013-07-24 12:32,2013-07-28 22:54,"",Invalid,2.3.1,"Hello,

I am actually finishing a migration from a project management software to redmine.

By doing so, I created many old versions which are now closed.

As you can see on image Version_List, many versions are still opened but finished such as :
* 5.1.4.1
* 5.1.4.2
* 5.1.4.3
* 5.1.4.4

as you can see on image Roadmap_Version.

When I click on the ""Settings/Versions/Close completed versions"" button, it doesn't close any of my finished versions.

I am actually running on Centos 6.4 with this environment :
<pre>
Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  no plugin installed
</pre>

Thank you."
14532,Redmine,Defect,"",Closed,High,Advanced_roadmap plugin,Иван Бухтияров,"",2013-07-28 12:42,Plugin Request,"","","","",0,2013-07-24 11:47,2013-07-28 12:42,"",Invalid,2.3.1,"I have installed Redmine 2.3.1.stable version. I have installed Advanced_roadmap plugin-0.8 by doing all instructions from installation guide. Everythig is ok. But when i try to add new milestone (from http://redmine_domain/projects/project_name/settings -> Milestones ->New milestone) I got internal error in browser. In redmine production.log I see:

> * SyntaxError (/usr/share/redmine/plugins/advanced_roadmap/app/controllers/milestones_controller.rb:123: Invalid char `\010' in expression
> * /usr/share/redmine/plugins/advanced_roadmap/app/controllers/milestones_controller.rb:128: Invalid char `\010' in expression):

What is the problem?"
14531,Redmine,Patch,"",Closed,Normal,Spanish translations for 2.3.x,Toshi MARUYAMA,"",2013-07-24 15:47,Translations,2.3.3,"","","",0,2013-07-24 11:38,2013-07-24 15:47,"","","",From #14521.
14528,Redmine,Defect,"",Closed,Normal,mySQL2 gem under Windows is failing for version 0.3.13,Matthew Houston,"",2014-08-10 03:11,Gems support,"","","","",0,2013-07-24 03:31,2014-08-10 03:11,"","",2.3.2,"Doing an upgrade under Windows from a working 2.1.2 install to 2.3.2.

The command 'bundle install --without test developement rmagick' is failing due to mySQL2 gem trying to install version 0.3.13.

It fails with the error 'Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.'

This wasn't noticed when upgrading to 2.3.1 (for testing).

Changing the gemfile to specifically point to version ""0.3.11"" rather than ""~> 0.3.11"" solved the issue for me.

Seems that there is an issue with the gem '0.3.13' which is buggering the install.

Thread located here:

http://www.redmine.org/boards/2/topics/38765

Ruby -v = 1.9.3p286
Redmine 2.1.2 -> 2.3.2"
14527,Redmine,Patch,"",New,Normal,Git-smart-http authentication by repository,Ciprian Ciubotariu,"",2013-07-24 00:16,SCM extra,"","","","",0,2013-07-23 17:05,"","","","","This patch allows the repository name to differ from the project name.

We migrated to a multi-repository per project setup after the whole infrastructure (scripts, build servers etc.) was set up. At this point we considered that renaming all the repositories to match the project identifier is too time-consuming and error-prone.

The compromise we found is to path the authentication script so that is also looks at the pool of repository identifiers when authenticating a git-smart-http request:

# extract the project/repository identifier from the request URI
# if it is a project identifier, use that project to authenticate the request
# if it is a repository identifier, use the first project it belongs to authenticate the request.

While this patch does not represent a full solution to the multi-repository problem, I hope it helps others in the same situation as us."
